#!/bin/sh
# Neko Console 一键安装（Docker Compose）
#
# 用法：
#   ./install.sh                  # 在当前目录安装（已有 docker-compose.yml 时直接用它）
#   ./install.sh --build          # 用当前源码本地构建镜像（不拉 ghcr）
#   ./install.sh --dir /opt/neko-console
#   curl -fsSL https://raw.githubusercontent.com/baizi51676-source/neko_console/main/install.sh | sh
set -eu

RAW_BASE=https://raw.githubusercontent.com/baizi51676-source/neko_console/main
BUILD=0
DIR=""

while [ $# -gt 0 ]; do
  case "$1" in
    --build) BUILD=1 ;;
    --dir) shift; DIR="${1:-}" ;;
    -h|--help) sed -n '2,12p' "$0"; exit 0 ;;
    *) echo "未知参数: $1"; exit 1 ;;
  esac
  shift
done

say()  { printf '\033[1;36m==>\033[0m %s\n' "$1"; }
warn() { printf '\033[1;33m[!]\033[0m %s\n' "$1"; }
die()  { printf '\033[1;31m[x]\033[0m %s\n' "$1"; exit 1; }

# ---------- 环境检查 ----------
command -v docker >/dev/null 2>&1 || die "未找到 docker，请先安装：https://docs.docker.com/engine/install/"

if docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"
else
  die "未找到 docker compose（v2 或 v1）"
fi
say "使用 $COMPOSE"

# ---------- 目录与文件 ----------
[ -n "$DIR" ] && { mkdir -p "$DIR"; cd "$DIR"; }
say "安装目录：$(pwd)"

if [ ! -f docker-compose.yml ]; then
  say "下载 docker-compose.yml"
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$RAW_BASE/docker-compose.yml" -o docker-compose.yml || die "下载失败（网络问题？可手动从仓库复制该文件）"
  elif command -v wget >/dev/null 2>&1; then
    wget -qO docker-compose.yml "$RAW_BASE/docker-compose.yml" || die "下载失败"
  else
    die "需要 curl 或 wget 下载 compose 文件"
  fi
fi

if [ ! -f .env ]; then
  say "生成 .env（直接回车使用默认值）"
  printf '  AstrBot 地址 [http://astrbot:6185]: '
  read -r ans_base || ans_base=""
  printf '  对外端口 [6186]: '
  read -r ans_port || ans_port=""
  printf '  侧车口令（可留空）: '
  read -r ans_pass || ans_pass=""
  {
    echo "# generated by install.sh on $(date '+%Y-%m-%d %H:%M:%S')"
    echo "ASTRBOT_BASE=${ans_base:-http://astrbot:6185}"
    echo "NEKO_PORT=${ans_port:-6186}"
    echo "NEKO_PASSWORD=${ans_pass:-}"
    echo "NEKO_MAX_PROXY_MB=6"
  } > .env
  chmod 600 .env
  say "已写入 .env"
else
  say "沿用已有 .env"
fi

# shellcheck disable=SC1091
. ./.env
PORT="${NEKO_PORT:-6186}"

# ---------- 启动 ----------
if [ "$BUILD" = "1" ]; then
  say "本地构建镜像（可能需要几分钟）"
  $COMPOSE build
else
  say "拉取镜像"
  if ! $COMPOSE pull; then
    warn "镜像拉取失败（ghcr 可能被墙或尚未发布），回退为本地构建"
    [ -f Dockerfile ] || die "当前目录没有 Dockerfile，无法本地构建；请 git clone 仓库后再用 --build"
    $COMPOSE build
  fi
fi

say "启动容器"
$COMPOSE up -d

# ---------- 等待健康 ----------
say "等待服务就绪"
i=0
while [ $i -lt 30 ]; do
  if command -v curl >/dev/null 2>&1; then
    code=$(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:${PORT}/__neko/api/health" || true)
  else
    code=$(wget -qO- "http://127.0.0.1:${PORT}/__neko/api/health" >/dev/null 2>&1 && echo 200 || echo 000)
  fi
  [ "$code" = "200" ] && break
  i=$((i + 1))
  sleep 2
done

if [ "${code:-000}" = "200" ]; then
  ip=$(hostname -I 2>/dev/null | awk '{print $1}')
  echo
  say "安装完成"
  echo "  本机访问：http://127.0.0.1:${PORT}/"
  [ -n "${ip:-}" ] && echo "  局域网访问：http://${ip}:${PORT}/"
  echo "  查看日志：$COMPOSE logs -f"
  echo "  停止服务：$COMPOSE down"
  echo
  echo "  提示：登录使用 AstrBot 控制台账号；侧车口令（若设置）与它不同。"
  echo "  若 AstrBot 与它不在同一 docker 网络，请把 .env 里的 ASTRBOT_BASE 改成宿主机可达地址。"
else
  warn "服务尚未通过健康检查，请查看日志：$COMPOSE logs --tail=50"
  exit 1
fi